# ==============================================================================
# TIMING CONSTRAINTS FOR SPARSEGUARD (DE10-Nano / Cyclone V)
# ==============================================================================

# 1. Define Main System Clock
# The DE10-Nano board provides a 50 MHz clock on PIN_V11 (Period = 20 ns).
create_clock -name "clk" -period 20.000 -waveform { 0.000 10.000 } [get_ports {clk}]

# 2. Derive Clock Uncertainty
# Automatically calculates and applies clock jitter and other margins for Cyclone V.
derive_clock_uncertainty

# 3. Asynchronous Inputs
# The reset pin (KEY0) is pressed manually and is asynchronous to the clock.
set_false_path -from [get_ports {rst_n}] -to *

# The SPI inputs (sclk, cs_n, mosi) are generated by an external Master.
# Because we oversample them using 3-stage synchronizers (CDC) inside spi_slave.sv,
# there is no synchronous setup/hold relationship required with the FPGA's 50MHz clock.
set_false_path -from [get_ports {spi_sclk spi_cs_n spi_mosi}] -to [all_registers]

# 4. Asynchronous Outputs
# The status LEDs are visual indicators and do not need strict setup/hold timing.
set_false_path -from * -to [get_ports {led_busy led_done led_alarm led_error}]

# The SPI MISO output is generated synchronously by our 50MHz clock but is captured 
# asynchronously by the external SPI Master's clock. 
set_false_path -from [all_registers] -to [get_ports {spi_miso}]
